class EnvConstants:
    GOOGLE_AI_API_KEY = "GOOGLE_AI_API_KEY"
    GOOGLE_CHAT_MODEL_NAME = "GOOGLE_CHAT_MODEL_NAME"
    GOOGLE_EMBEDDING_MODEL_NAME = "GOOGLE_EMBEDDING_MODEL_NAME"
    TEST_ACCESS_TOKEN = "TEST_ACCESS_TOKEN"
    QDRANT_CLIENT_URL = "QDRANT_CLIENT_URL"
    AUTH_USERNAME = "AUTH_USERNAME"
    AUTH_PASSWORD = "AUTH_PASSWORD"
    
    